# Generated by Django 5.2.4 on 2025-07-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=2000)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('message_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'received_messages',
                'ordering': ['-received_at'],
            },
        ),
    ]
